import SideBar from "@/app/SideBar";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { Flex, Theme } from "@radix-ui/themes";
import "@radix-ui/themes/styles.css";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import { BreadcrumbBar } from "./BreadCrumbBar";
import "./globals.css";
import AuthProvider from "@/app/auth/Provider";

const getRoboto = Roboto({
  weight: "400",
  variable: "--font-roboto",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type IconName = "LayoutDashboard" | "ClipboardList" | "User";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const menuItems: { title: string; url: string; iconName: IconName }[] = [
    {
      title: "Dashboard",
      url: "/",
      iconName: "LayoutDashboard",
    },
    {
      title: "Issues",
      url: "/issues",
      iconName: "ClipboardList",
    },
    {
      title: "Users",
      url: "/users",
      iconName: "User",
    },
  ];

  return (
    <html lang="en">
      <body className={`${getRoboto.className} antialiased`}>
        <AuthProvider>
          <Theme appearance="light" accentColor="violet">
            <SidebarProvider>
              <SideBar menuItems={menuItems} />
              <main className="p-5 w-full space-y-5">
                <Flex gap="3" align="center">
                  <SidebarTrigger />
                  <BreadcrumbBar />
                </Flex>
                <div className="lg:mx-10">{children}</div>
              </main>
            </SidebarProvider>
          </Theme>
        </AuthProvider>
      </body>
    </html>
  );
}
